Feature/hipchat
fsfw-dresden/homepage-2.0-content pull request #6
Opened 2017-05-02 19:36 UTC by cooox

After first reviews I changed some parts and finished the draft.
Please leave editorial feedback here and I will include them.

2017-05-03 14:14 UTC, sebastianriese requested changes
Insgesamt vielleicht einen Hauch zu ideologisch (finde ich aber nicht so schlimm). Ansonsten habe ich ein paar Typos gefunden.

2017-05-03 14:14 UTC, sebastianriese commented on 2017/hipchat-breakin.md
> +die Software bei Atlassian lizenziert, kann aber auf einem eigenen Server instaliert
Typo: instaliert => installiert

2017-05-03 14:14 UTC, sebastianriese commented on 2017/hipchat-breakin.md
> +
Während ich zustimme, dass man AI keine gesellschaftlichen Entscheidungen anvertrauen sollte, zweifle ich an der These von sexistischen AI-Algorithmen. (Und man muss natürlich das Training auch immer von den zugrundeliegenden Algorithmen trennen).

2017-05-03 14:14 UTC, sebastianriese commented on 2017/hipchat-breakin.md
> +Daher mein Appell: die IT muss sich ihrer wachsenden Verantwortung bewusster werden
Nach den deutschen orthographischen Konventionen muss (soweit ich weiß) das Wort nach einem Doppelpunkt immer groß geschrieben werden.

2017-05-09 07:40 UTC, s72785 commented
also ich finde den Artikel durchaus gelungen. ein paar Gedanken habe ich angemerkt.

2017-05-09 08:20 UTC, Nos- commented
Hey klasse Arbeit!
Beim Durchlesen der Änderungen hätte ich gern ein paar Kommentare hinterlassen, was aber irgendwie nicht ging. Ich schau nun nochmal an anderer Stelle.

2017-05-09 08:30 UTC, s72785 commented
@Nos- evtl. fehlt dir etwas mehr JavaScript? enn die Autovervollständigung im Editor funktioniert dürfte auch die Kommentierung unter einem Commit gehen. Dort auf die Zeilennummer hovern und das blau hinterlegte Plus-Zeichen klicken.

2017-05-09 10:56 UTC, s72785 reviewed
nichts dringliches…

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
>  zur Verwaltung von Kunden und Aufträgen, und die Kundendaten dieser SaaS-Plattform
evtl. Hinweis auf [SaaSS]: https://www.gnu.org/philosophy/who-does-that-server-really-serve.de.html

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
>  beinhaltet. Es ist im 21. Jahrhundert einfach nicht mehr akzeptabel, als Bürger
s/beinhaltet/nach sich zieht/

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
> +
* angibt welche Daten zu welchen Zwecken erhoben werden

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
> +Leider bringt dies Arbeit mit sich. Die Software muss installiert und gewartet,
Arbeit: bzw. Kosten für diese Dienstleistung

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
> +
Beispiele in teils anarchistiger Tradition von u.a. Kollektiven/Genossenschfatlichen Projekten die dergleichen tun?
Datenkolektiv, in-berlin, {ein Aussteller von CLT 2015}, andere?

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
> +Und dafür lohnt sich die Arbeit! Wer will schon eigene
s/die Arbeit/der zusätzliche Aufwand/

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
> +Plattformen [mehr und mehr an politischem Gewicht gewinnen][denmark-digital-ambassador].
vgl. Verlage und große Verwerter zur Gesetzgebeung der Verwertungsrechte

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
> +Datenschutz und Software-Regularien für überholt
(d.h. auch Verbraucherschutz)

2017-05-09 10:56 UTC, s72785 commented on 2017/hipchat-breakin.md
> +ermöglicht, Profile, Netzwerke und Wirtschaftsinformationen aufzubereiten legt Byte für
s/aufzubereiten legt/zahlt nicht nur mit diesen, sondern legt/

2017-05-09 13:13 UTC, cooox commented on 2017/hipchat-breakin.md
> +Daher mein Appell: die IT muss sich ihrer wachsenden Verantwortung bewusster werden
Sehr wahrscheinlich hast du Recht, siehe [Regel 93](http://www.duden.de/sprachwissen/rechtschreibregeln/Gro%C3%9F-%20und%20Kleinschreibung).

2017-05-09 13:16 UTC, cooox commented on 2017/hipchat-breakin.md
>  zur Verwaltung von Kunden und Aufträgen, und die Kundendaten dieser SaaS-Plattform
Siehe `[stallman-saas]: https://www.gnu.org/philosophy/who-does-that-server-really-serve.html` im letzen Teil.

2017-05-09 13:19 UTC, cooox commented on 2017/hipchat-breakin.md
> +
Darauf muss ich mich aber nicht im Sinne des Vertrauens verlassen können. Eine Angabe von Seiten des Anbieters über die Datennutzung kann ich einsehen oder eben nicht.

2017-05-09 13:24 UTC, s72785 commented on 2017/hipchat-breakin.md
> +
jain: oder du kannst sie einsehen und er überlegt es sich dann anders; wahlweise benachrichtigt er dich oder auch nicht

2017-05-09 13:39 UTC, cooox commented on 2017/hipchat-breakin.md
> +
Darüber können wir ja mal im Plenum diskutieren :smiley:

2017-05-14 08:31 UTC, cooox commented
@sebastianriese Please review changes and merge if possible

2017-05-18 08:42 UTC, cknoll commented on 2017/hipchat-breakin.md
> +[Diaspora][diaspora], [Mastodon][mastodon], [Rocket.chat][rocketchat], [Kanboard][kanboard]
Eventuell könnte man hier noch https://about.mattermost.com/slack-vs-mattermost/ erwähnen. Es tritt explizit als freie Alternative zu Slack (und HipChat?) an.

2017-05-18 08:46 UTC, cknoll commented on 2017/hipchat-breakin.md
> +Facebook, SaaS wie Slack oder Smartphone-Apps wie WhatsApp nutzt muss lernen welche Folgen dies
nutzt {Komma} muss

2017-05-18 08:51 UTC, cknoll commented on 2017/hipchat-breakin.md
> +Erstens: der Konsument bzw. Kunde eines Softwareprodukts. **Du machst durch deine
Evtl. 1. und 2. (als Ordnungszahle) schreiben? Das lockert den Text auf, wenn man bloß mal drüberscrollt, steigt man da ggf. (wieder) ein.

2017-05-18 08:53 UTC, cknoll commented on 2017/hipchat-breakin.md
> +veröffentlichen, die dann in Monopol- oder Militärsoftware integriert werden!
Könnte man hier vielleicht auch auf MIT/BSD vs GPL eingehen? (Vermutlich wäre das aber auch Stoff für einen weiteren Blogartikel, @horazont?)

2017-05-18 08:54 UTC, cknoll commented on 2017/hipchat-breakin.md
> +Die Informatik muss sich öffnen und aus der Blase hinaustreten. Es ist schön zu einem kleinen
schön {Komma} zu

2017-05-18 08:58 UTC, cknoll commented on 2017/hipchat-breakin.md
> +
1. würde ich weniger Ausrufzeichen verwenden, also hier weglassen.
2. Das AI-Problem ist ja nur eins. Das Sammeln und zentrale Vorhalten von Daten an sich ist ja schon problematisch. Die Botschaft könnte hier sein: ohne eine halbwegs funktionierende Gesellschaft sind IT-Kenntnisse überflüssig und wertlos

2017-05-18 09:00 UTC, cknoll commented on 2017/hipchat-breakin.md
> +nutzen geben implizit ihre Zustimmung** zur Art und Weise, wie dieser Dienst
nutzen {Komma} geben

2017-05-18 09:01 UTC, cknoll commented on 2017/hipchat-breakin.md
> +die Plattform interessiert das Null, aber man selbst ist verlockt zu denken etwas
zu denken {Komma} etwas

2017-05-18 09:04 UTC, cknoll commented on 2017/hipchat-breakin.md
> +Daher mein Appell: Die IT muss sich ihrer wachsenden Verantwortung bewusster werden
Ich habe den Eindruck, der Absatz vorher richtet sich eher an Nutzer*Innen, der Appell aber an "die IT". Vielleicht könnte man den Appell auch in zwei Teile gliedern 1. User, 2. IT.

2017-05-18 09:09 UTC, cknoll commented on 2017/hipchat-breakin.md
> +
Ggf. sowas ergänzen:
Für Fragen oder Anregungen nehmt gerne Kontakt zu [uns][FSFW] auf.

2017-05-18 15:48 UTC, merged